
server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: controller-web
          uri: lb://WEB-CONTROLLER
          predicates:
            - Path= /controller/**
          filters:
            - StripPrefix=1

  application:
    name: web-gateway